---
- name: "Update Packages"
  become: yes
  apt:
    update_cache: yes

- name: "Install NodeJS and NPM and pm2"
  become: yes
  apt:
    name: ['nodejs', 'npm', 'pm2']
    state: latest
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"
