---
- name: "Update Packages"
  become: yes
  apt:
    update_cache: yes

- name: "Install NodeJS and NPM "
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: "yes"

- npm:
  name: pm2
  global: yes
